apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ui2-integration-gradle-cache
  namespace: ui2-build
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
