-- Exactly the four Product Owner approved committed Panorama policy reads.
SELECT set_config('app.actor_fingerprint', 'migration:V117_pan_policy_reads', true);
SELECT set_config('app.action_id', 'gate_registry_insert_by_migration', true);
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer, canonical_command_key)
VALUES ('pan_policy_shared', 'palo_alto', 'panorama', 'not_applicable', 'PAN_XML_API', 'read', 'SIGNED_OFF', 60, 'none', 'manual admin request; automatic at most once per Panorama per 6 hours', 'one existing-authentication API key per job; serial', 'fail closed; preserve previous snapshots', 'sensitive configuration; parse bounded XML in memory; no raw retention', '["outcome", "deviceGroupCount", "ruleCount"]', 'docs/design/PO_DECISION_RECORD_2026_10_01_PAN_POLICY_READS.md', 'type=config&action=show&xpath=/config/shared');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer, canonical_command_key)
VALUES ('pan_policy_device_group', 'palo_alto', 'panorama', 'not_applicable', 'PAN_XML_API', 'read', 'SIGNED_OFF', 60, 'none', 'manual admin request; automatic at most once per Panorama per 6 hours', 'one existing-authentication API key per job; serial', 'fail closed; preserve previous snapshots', 'sensitive configuration; parse bounded XML in memory; no raw retention', '["outcome", "deviceGroupCount", "ruleCount"]', 'docs/design/PO_DECISION_RECORD_2026_10_01_PAN_POLICY_READS.md', 'type=config&action=show&xpath=/config/devices/entry[@name=''localhost.localdomain'']/device-group/entry[@name=''<DG>'']');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer, canonical_command_key)
VALUES ('pan_policy_devicegroups', 'palo_alto', 'panorama', 'not_applicable', 'PAN_XML_API', 'read', 'SIGNED_OFF', 60, 'none', 'manual admin request; automatic at most once per Panorama per 6 hours', 'one existing-authentication API key per job; serial', 'fail closed; preserve previous snapshots', 'sensitive configuration; parse bounded XML in memory; no raw retention', '["outcome", "deviceGroupCount", "ruleCount"]', 'docs/design/PO_DECISION_RECORD_2026_10_01_PAN_POLICY_READS.md', 'type=op&cmd=<show><devicegroups/></show>');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer, canonical_command_key)
VALUES ('pan_policy_hierarchy', 'palo_alto', 'panorama', 'not_applicable', 'PAN_XML_API', 'read', 'SIGNED_OFF', 60, 'none', 'manual admin request; automatic at most once per Panorama per 6 hours', 'one existing-authentication API key per job; serial', 'fail closed; preserve previous snapshots', 'sensitive configuration; parse bounded XML in memory; no raw retention', '["outcome", "deviceGroupCount", "ruleCount"]', 'docs/design/PO_DECISION_RECORD_2026_10_01_PAN_POLICY_READS.md', 'type=op&cmd=<show><dg-hierarchy></dg-hierarchy></show>');
