-- PO 2026-10-05: exact approved CP MDS inventory and hit reads.
SELECT set_config('app.actor_fingerprint', 'migration:V124_cp_policy_object_inventory', true);
SELECT set_config('app.action_id', 'gate_registry_update_by_migration', true);
UPDATE gate_registry SET sign_off_state = 'SIGNED_OFF',
    source_document_pointer = 'PO 2026-10-05; cp-objects-hits-collect; approved hits read'
WHERE gate_id = 'cp_policy_access_rulebase_hits' AND sign_off_state = 'DRAFTED';
SELECT set_config('app.action_id', 'gate_registry_insert_by_migration', true);
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_packages_50', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-packages limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_times', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-times limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_time_groups', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-time-groups limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_gateways_and_servers', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-gateways-and-servers limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_hosts', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-hosts limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_networks', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-networks limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_groups', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-groups limit 50 offset ''<N>'' details-level full dereference-group-members false', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_groups_with_exclusion', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-groups-with-exclusion limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_address_ranges', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-address-ranges limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_services_tcp', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-services-tcp limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_services_udp', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-services-udp limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_services_icmp', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-services-icmp limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_services_icmp6', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-services-icmp6 limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_services_other', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-services-other limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_services_sctp', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-services-sctp limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_services_dce_rpc', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-services-dce-rpc limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_services_rpc', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-services-rpc limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_service_groups', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-service-groups limit 50 offset ''<N>'' details-level full dereference-group-members false', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_access_roles', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-access-roles limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_dynamic_objects', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-dynamic-objects limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_dns_domains', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-dns-domains limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_security_zones', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-security-zones limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');
INSERT INTO gate_registry (gate_id, vendor, platform_role_scope, shell_context, transport_kind, canonical_command_key, action_class, sign_off_state, timeout_s, retry_rule, max_frequency, session_reuse_rule, unsupported_behavior_ref, secret_output_risk, safe_telemetry_fields, source_document_pointer)
VALUES ('cp_policy_unused_objects', 'check_point', 'cp_multi_domain_server', 'expert', 'SSH_EXEC', 'mgmt_cli -r true -d ''<DOMAIN>'' -f json show-unused-objects limit 50 offset ''<N>'' details-level full', 'read', 'SIGNED_OFF', 300, 'none', 'manual policy request; automatic at most once per domain per 6 hours', 'existing policy SSH sessions; bounded adaptive concurrency', 'UNKNOWN; per-domain per-type gap; packages remain available', 'sensitive object data; parse in memory; no raw retention', '["outcome", "pages", "objects", "seconds"]', 'PO 2026-10-05; cp-objects-hits-collect; approved CLASS_0 reads');

-- One latest parsed type per source/domain, including explicit failed/unsupported states.
CREATE TABLE cp_policy_object_inventory (
    source_id TEXT NOT NULL,
    domain_ref TEXT NOT NULL,
    object_type TEXT NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    snapshot JSONB NOT NULL CHECK (jsonb_typeof(snapshot) = 'object'),
    PRIMARY KEY (source_id, domain_ref, object_type)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON cp_policy_object_inventory TO ui2_app;
