#!/usr/bin/env python3
"""Render the design-record successor index."""
from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / "docs" / "design"
INDEX = DESIGN / "DECISION_RECORD_SUCCESSOR_INDEX.md"
STATUS = re.compile(r"^#{2,6} Status\s*$", re.MULTILINE)
H1 = re.compile(r"^# (.+)$", re.MULTILINE)
RELATION = re.compile(
    r"\b((?:defect-)?correcting amendment to|successor (?:amendment|clause) to|amends?|supersedes|narrows?)\b",
    re.IGNORECASE,
)
DATE = re.compile(r"\b(20\d{2}-\d{2}-\d{2})\b")


@dataclass(frozen=True)
class Record:
    name: str
    subject: str
    date: str
    relation: str = "standalone"
    target: str = ""


def _first_paragraph(text: str) -> str:
    return " ".join(re.split(r"\n\s*\n", text.strip(), maxsplit=1)[0].split())


def _status_block(text: str) -> str:
    match = STATUS.search(text)
    if match:
        return _first_paragraph(text[match.end():])
    title = H1.search(text)
    return _first_paragraph(text[title.end():]) if title else ""


def _subject(text: str, fallback: str) -> str:
    match = H1.search(text)
    return match.group(1).strip() if match else fallback


def records() -> list[Record]:
    docs = {path.name for path in DESIGN.glob("*.md") if path != INDEX}
    docs.update(path.name for path in ROOT.glob("*.md"))
    result: list[Record] = []
    for path in sorted(DESIGN.glob("*.md")):
        if path == INDEX:
            continue
        text = path.read_text(encoding="utf-8")
        block = _status_block(text)
        match = RELATION.search(block)
        relation, target = "standalone", ""
        if match:
            candidate_relation = " ".join(match.group(1).lower().split())
            candidates = re.findall(r"[A-Za-z0-9_.-]+\.md", block[match.end():])
            target = next((Path(value).name for value in candidates if Path(value).name in docs), "")
            if target:
                relation = candidate_relation
        result.append(Record(
            path.name,
            _subject(text, path.stem),
            (DATE.search(block).group(1) if DATE.search(block) else "—"),
            relation,
            target,
        ))
    return result


def unresolved(records_: list[Record]) -> list[Record]:
    return [record for record in records_ if record.relation != "standalone" and not record.target]


def render() -> str:
    rows = records()
    lines = [
        "# Decision-record successor index",
        "",
        "Generated by `python3 scripts/successor_index.py render`; do not edit by hand.",
        "",
        "## Records",
        "",
        "| Record | Relation | Target | Date | Subject |",
        "| --- | --- | --- | --- | --- |",
    ]
    for record in rows:
        target = f"`{record.target}`" if record.target else "—"
        lines.append(f"| `{record.name}` | {record.relation} | {target} | {record.date} | {record.subject} |")
    lines.extend(["", "## Chains", ""])
    targets = sorted({record.target for record in rows if record.target})
    for target in targets:
        lines.extend([f"### `{target}`", ""])
        for record in rows:
            if record.target == target:
                lines.append(f"- `{record.name}` — {record.relation} ({record.date})")
        lines.append("")
    standalone = [record for record in rows if record.relation == "standalone"]
    lines.extend(["### Standalone", ""])
    lines.extend(f"- `{record.name}` ({record.date})" for record in standalone)
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", nargs="?", choices=("render",), default="render")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = render()
    bad = unresolved(records())
    if bad:
        parser.error("unresolved status relation(s): " + ", ".join(record.name for record in bad))
    if args.check:
        return 0 if INDEX.exists() and INDEX.read_text(encoding="utf-8") == output else 1
    INDEX.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
